apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 10.9.2
    helm:
      releaseName: argocd
      valuesObject:
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: argocd.home.arpa
            path: /
            pathType: Prefix
            tls: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
